const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{Sprite2: 0},
	{佛藝: 0},
	{佛藝_: 0},
	{佛藝_4: 0},
	{鍵盤: 0},
	{音頻: 0},
	{Sprite: 0},
	{移動到: 0},
	{mondstadt_wallpaper_by_jessa_daeh_dgt8rhspre: 0},
	{Sprite3: 0},
	{佛藝_3: 0},
	{Text: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{螢幕擷取畫面: 0},
	{螢幕擷取畫面2: 0},
	{black: 0},
	{black2: 0},
	{ches: 0},
	{wait: 0},
	{game: 0}
];

self.InstanceType = {
	Sprite2: class extends self.ISpriteInstance {},
	佛藝: class extends self.ISpriteInstance {},
	佛藝_: class extends self.ISpriteInstance {},
	佛藝_4: class extends self.ISpriteInstance {},
	鍵盤: class extends self.IInstance {},
	音頻: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	mondstadt_wallpaper_by_jessa_daeh_dgt8rhspre: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	佛藝_3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	螢幕擷取畫面: class extends self.ISpriteInstance {},
	螢幕擷取畫面2: class extends self.ISpriteInstance {}
}